runtime: nodejs20
instance_class: F2
handlers:
    # Serve all static files with url ending with a file extension
    - url: /(.*\..+)$
      static_files: build/live/\1
      upload: build/live/(.*\..+)$
    # Catch all handler to index.html
    - url: /.*
      static_files: build/live/index.html
      upload: build/live/index.html
